version: '3.9'
services:
  server:
    build: .
    command: ["./wait-for-postgres.sh", "db:5432", "-t", "600000000", "--", "./mini-social-app"]
    ports:
      - "8080:8080"
    depends_on:
      - db
  
  db:
    restart: always
    image: postgres:13.3
    # env_file:
    #   - .env
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=dbname
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    restart: on-failure
    image: migrate/migrate
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    command: [
      "-path",
      "/migrations",
      "-database",
      "postgres://root:secretpassword@db:5432/dbname?sslmode=disable", "up",
    ]
    links:
      - db

