version: '3.9'
services:
  server:
    build: .
    command: ["./wait-for-postgres.sh", "db:5432", "-t", "600000000", "--", "./mini-social-app"]
    ports:
      - "8080:8080"
    depends_on:
      - db
  
  db:
    restart: always
    image: postgres:15.3
    env_file:
      - .env
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
