version: '3.9'
services:
  server:
    build: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    restart: always
    image: postgres:13.3
    env_file:
      - .env
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
