server:
  port: 8080
  host: "localhost"
  hash_salt: "hash_salt"
  signing_key: "signing_key"
database:
  host: "localhost"
  port: 5432
  username: "root"
  password: "secretpassword"
  name: "dbname"
